version: "3.9"

services:

  db:
    image: postgres:16
    container_name: postgres_porteur
    environment:
      POSTGRES_DB: porteurProjetdb
      POSTGRES_USER: porteurUser
      POSTGRES_PASSWORD: porteurPass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - porteur_network

  app:
    build: .
    container_name: porteurDev_app
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - porteur_network

networks:
  porteur_network:

volumes:
  postgres_data:
